# Ejercicios Pandas

Tras hacer tus propias pruebas con la teoría de Pandas, completa los siguientes ejercicios en orden:

---
## Ejercicio 1

Al igual que con NumPy, tendrás que importar las librerías necesarias para poder trabajar:

In [31]:
import pandas as pd
import numpy as np

---
## Ejercicio 2

Crea una serie a partir de un diccionario con al menos 3 elementos. Muestra por pantalla la serie:

In [32]:
diccionario = {
    "a": 1,
    "b": 2,
    "c": 3,
}
serie = pd.Series(diccionario)
serie

a    1
b    2
c    3
dtype: int64

---
## Ejercicio 3

Crea una matriz de NumPy con al menos 3 filas y 3 columnas. A partir de esta, crea un dataframe, teniendo en cuenta que la primera fila serán los nombres de las columnas y la primera columna los índices de las filas. Muestra el DataFrame por pantalla:

In [33]:
matriz = np.array([
    ['', 'Columna1', 'Columna2', 'Columna3'],
    ['A', 10, 20, 30],
    ['B', 40, 50, 60],
    ['C', 70, 80, 90]
])
df = pd.DataFrame(
    # En data se guardan los valores (todo excepto la primera fila y la primera columna)
    data=matriz[1:, 1:],
    # En index se guarda la primera columna
    index=matriz[1:, 0],
    # En column se guarda la priemra fila
    columns=matriz[0, 1:]
)
df

  Columna1 Columna2 Columna3
A       10       20       30
B       40       50       60
C       70       80       90

---
## Ejercicio 4

Crea una matriz 10x5 de números enteros comprendidos entre el 0 y el 9 con Numpy. Después, crea un DataFrame a partir de esta sin indicar columnas ni índice para las filas y muestralo por pantalla:

In [34]:
matriz = np.random.randint(0, 10, [10,5])
df = pd.DataFrame(matriz)
df

   0  1  2  3  4
0  1  0  1  9  8
1  6  7  0  2  7
2  2  7  3  0  5
3  9  9  0  8  5
4  9  8  7  1  7
5  8  2  1  5  6
6  4  0  5  8  1
7  2  7  4  5  5
8  4  8  7  4  2
9  3  0  8  9  1

---
## Ejercicio 5

Del DataFrame creado en el ejercicio anterior, muestra su forma, índice, número de filas, media por columnas, valores máximos y mínimos por columnas, mediana por columnas y la desviación típica por columnas:

In [35]:
print(f"Forma: {df.shape}")
print(f"Índice: {df.index}")
print(f"Número de filas: {len(df)}")
print(f"Media por columnas:\n{df.mean()}")
print(f"Valores máximos por columnas:\n{df.max()}")
print(f"Valores mínimos por columnas:\n{df.min()}")
print(f"Mediana por columnas:\n{df.median()}")
print(f"Desviación típica por columnas:\n{df.std()}")

Forma: (10, 5)
Índice: RangeIndex(start=0, stop=10, step=1)
Número de filas: 10
Media por columnas:
0    4.8
1    4.8
2    3.6
3    5.1
4    4.7
dtype: float64
Valores máximos por columnas:
0    9
1    9
2    8
3    9
4    8
dtype: int32
Valores mínimos por columnas:
0    1
1    0
2    0
3    0
4    1
dtype: int32
Mediana por columnas:
0    4.0
1    7.0
2    3.5
3    5.0
4    5.0
dtype: float64
Desviación típica por columnas:
0    3.011091
1    3.794733
2    3.062316
3    3.348300
4    2.540779
dtype: float64

---
## Ejercicio 6

Crea un DataFrame a partir de una matriz con valores definidos por tí. Estos valores deberán incluir valores nulos. Luego muestra la cantidad de valores nulos por pantalla y modifica los valores nulos por la media que tenga dicha columna sin incluir los nulos. Muestra el resultado por pantalla:

In [41]:
matriz = np.array([
    [10, np.nan, 30],
    [40, 50, np.nan],
    [np.nan, 80, 90],
    [100, np.nan, 120]
])
df = pd.DataFrame(
    data= matriz,
    columns= ["Columna1", "Columna2", "Columna3"]
)
df.isna().sum()
df_filled = df.fillna(df.mean())
df_filled

   Columna1  Columna2  Columna3
0      10.0      65.0      30.0
1      40.0      50.0      80.0
2      50.0      80.0      90.0
3     100.0      65.0     120.0

---
## Ejercicio 7

Importa en DataFrames distintos, al menos los datos de un CSV y un JSON contenidos en el fichero comprimido "02-Pandas_ficheros.zip". Muestra por pantalla la descripción básica de los datos de cada una de ellas:

In [44]:
df_csv = pd.read_csv("02-Pandas_Ficheros_1/california_housing_train.csv")
df_json = pd.read_json("02-Pandas_Ficheros_1/anscombe.json")
print("CSV")
print(df_csv.describe())
print("\nJSON")
print(df_json.describe())

CSV
          longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000
mean    -119.562108     35.625225           28.589353   2643.664412
std        2.005166      2.137340           12.586937   2179.947071
min     -124.350000     32.540000            1.000000      2.000000
25%     -121.790000     33.930000           18.000000   1462.000000
50%     -118.490000     34.250000           29.000000   2127.000000
75%     -118.000000     37.720000           37.000000   3151.250000
max     -114.310000     41.950000           52.000000  37937.000000

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000
mean       539.410824   1429.573941    501.221941       3.883578
std        421.499452   1147.852959    384.520841       1.908157
min          1.000000      3.000000      1.000000       0.499900
25%        297.000000    790.000000    282.000000       2.566375
50%        434.000000   1167.000000    409.000000       3.544600
75%        648.250000   1721.000000    605.250000       4.767000
max       6445.000000  35682.000000   6082.000000      15.000100

       median_house_value
count        17000.000000
mean        207300.912353
std         115983.764387
min          14999.000000
25%         119400.000000
50%         180400.000000
75%         265000.000000
max         500001.000000

JSON
               X          Y
count  44.000000  44.000000
mean    9.000000   7.500455
std     3.198837   1.959244
min     4.000000   3.100000
25%     7.000000   6.117500
50%     8.000000   7.520000
75%    11.000000   8.747500
max    19.000000  12.740000

---
## Ejercicio 8

Crea una matriz aleatoria 100x3 de números comprendidos entre el 0 y el 1 con Numpy. Exportala tanto a un fichero CSV como a un fichero JSON y comprueba el resultado abriendo dichos ficheros:

In [48]:
matriz = np.random.randint(0, 1, [100, 3])
df = pd.DataFrame(matriz)
df.to_csv("matrizEj8CSV.csv")
df.to_json("matrizEj8JSON.json")

---
## Ejercicio 9

Investiga qué es la correlación entre columnas. Cuando lo hayas entendido, crea una matriz 10x3 con datos manuales que entre la primera y segunda columna de una correlación de 1 en ambos sentidos. Muestra la matriz y su correlación entre columnas por pantalla:

---
## Ejercicio 10

En vuestros ordenadores, MySQLServer debería estar instalado. De no ser así instálalo. Una vez hecho eso, crea un esquema llamado "BDIA" y a continuación lanza las sentencias SQL del fichero "02-Pandas_Tabla_MySQL.sql". Por último, trata de importar los datos desde la base de datos con Pandas en un DataFrame y muéstralos por pantalla:

In [ ]:
#TODO
import mysql.connector

conn = mysql.connector.connect(
    host = "localhost",
    user = "root",
    password = "",
    database = "pandas"
)

ProgrammingError: 1049 (42000): Unknown database 'pandas'