# Ejercicios Pandas

Tras hacer tus propias pruebas con la teoría de Pandas, completa los siguientes ejercicios en orden:

---
## Ejercicio 1

Al igual que con NumPy, tendrás que importar las librerías necesarias para poder trabajar:

In [2]:
import pandas as pd
import numpy as np

---
## Ejercicio 2

Crea una serie a partir de un diccionario con al menos 3 elementos. Muestra por pantalla la serie:

In [3]:
diccionario = {
    "a": 1,
    "b": 2,
    "c": 3,
}
serie = pd.Series(diccionario)
serie

a    1
b    2
c    3
dtype: int64

---
## Ejercicio 3

Crea una matriz de NumPy con al menos 3 filas y 3 columnas. A partir de esta, crea un dataframe, teniendo en cuenta que la primera fila serán los nombres de las columnas y la primera columna los índices de las filas. Muestra el DataFrame por pantalla:

In [4]:
matriz = np.array([
    ['', 'Columna1', 'Columna2', 'Columna3'],
    ['A', 10, 20, 30],
    ['B', 40, 50, 60],
    ['C', 70, 80, 90]
])
df = pd.DataFrame(
    # En data se guardan los valores (todo excepto la primera fila y la primera columna)
    data=matriz[1:, 1:],
    # En index se guarda la primera columna
    index=matriz[1:, 0],
    # En column se guarda la priemra fila
    columns=matriz[0, 1:]
)
df

  Columna1 Columna2 Columna3
A       10       20       30
B       40       50       60
C       70       80       90

---
## Ejercicio 4

Crea una matriz 10x5 de números enteros comprendidos entre el 0 y el 9 con Numpy. Después, crea un DataFrame a partir de esta sin indicar columnas ni índice para las filas y muestralo por pantalla:

In [5]:
matriz = np.random.randint(0, 10, [10,5])
df = pd.DataFrame(matriz)
df

   0  1  2  3  4
0  1  9  4  8  1
1  1  3  0  8  8
2  1  8  4  8  5
3  1  6  4  3  7
4  1  6  6  5  0
5  3  2  1  9  6
6  9  7  9  9  3
7  7  9  9  1  6
8  1  0  4  8  1
9  6  1  1  6  0

---
## Ejercicio 5

Del DataFrame creado en el ejercicio anterior, muestra su forma, índice, número de filas, media por columnas, valores máximos y mínimos por columnas, mediana por columnas y la desviación típica por columnas:

In [6]:
print(f"Forma: {df.shape}")
print(f"Índice: {df.index}")
print(f"Número de filas: {len(df)}")
print(f"Media por columnas:\n{df.mean()}")
print(f"Valores máximos por columnas:\n{df.max()}")
print(f"Valores mínimos por columnas:\n{df.min()}")
print(f"Mediana por columnas:\n{df.median()}")
print(f"Desviación típica por columnas:\n{df.std()}")

Forma: (10, 5)
Índice: RangeIndex(start=0, stop=10, step=1)
Número de filas: 10
Media por columnas:
0    3.1
1    5.1
2    4.2
3    6.5
4    3.7
dtype: float64
Valores máximos por columnas:
0    9
1    9
2    9
3    9
4    8
dtype: int32
Valores mínimos por columnas:
0    1
1    0
2    0
3    1
4    0
dtype: int32
Mediana por columnas:
0    1.0
1    6.0
2    4.0
3    8.0
4    4.0
dtype: float64
Desviación típica por columnas:
0    3.071373
1    3.348300
2    3.119829
3    2.718251
4    3.056868
dtype: float64

---
## Ejercicio 6

Crea un DataFrame a partir de una matriz con valores definidos por tí. Estos valores deberán incluir valores nulos. Luego muestra la cantidad de valores nulos por pantalla y modifica los valores nulos por la media que tenga dicha columna sin incluir los nulos. Muestra el resultado por pantalla:

In [7]:
matriz = np.array([
    [10, np.nan, 30],
    [40, 50, np.nan],
    [np.nan, 80, 90],
    [100, np.nan, 120]
])
df = pd.DataFrame(
    data= matriz,
    columns= ["Columna1", "Columna2", "Columna3"]
)
df.isna().sum()
df_filled = df.fillna(df.mean())
df_filled

   Columna1  Columna2  Columna3
0      10.0      65.0      30.0
1      40.0      50.0      80.0
2      50.0      80.0      90.0
3     100.0      65.0     120.0

---
## Ejercicio 7

Importa en DataFrames distintos, al menos los datos de un CSV y un JSON contenidos en el fichero comprimido "02-Pandas_ficheros.zip". Muestra por pantalla la descripción básica de los datos de cada una de ellas:

In [8]:
df_csv = pd.read_csv("02-Pandas_Ficheros_1/california_housing_train.csv")
df_json = pd.read_json("02-Pandas_Ficheros_1/anscombe.json")
print("CSV")
print(df_csv.describe())
print("\nJSON")
print(df_json.describe())

CSV
          longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000
mean    -119.562108     35.625225           28.589353   2643.664412
std        2.005166      2.137340           12.586937   2179.947071
min     -124.350000     32.540000            1.000000      2.000000
25%     -121.790000     33.930000           18.000000   1462.000000
50%     -118.490000     34.250000           29.000000   2127.000000
75%     -118.000000     37.720000           37.000000   3151.250000
max     -114.310000     41.950000           52.000000  37937.000000

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000
mean       539.410824   1429.573941    501.221941       3.883578
std        421.499452   1147.852959    384.520841       1.908157
min          1.000000      3.000000      1.000000       0.499900
25%        297.000000    790.000000    282.000000       2.566375
50%        434.000000   1167.000000    409.000000       3.544600
75%        648.250000   1721.000000    605.250000       4.767000
max       6445.000000  35682.000000   6082.000000      15.000100

       median_house_value
count        17000.000000
mean        207300.912353
std         115983.764387
min          14999.000000
25%         119400.000000
50%         180400.000000
75%         265000.000000
max         500001.000000

JSON
               X          Y
count  44.000000  44.000000
mean    9.000000   7.500455
std     3.198837   1.959244
min     4.000000   3.100000
25%     7.000000   6.117500
50%     8.000000   7.520000
75%    11.000000   8.747500
max    19.000000  12.740000

---
## Ejercicio 8

Crea una matriz aleatoria 100x3 de números comprendidos entre el 0 y el 1 con Numpy. Exportala tanto a un fichero CSV como a un fichero JSON y comprueba el resultado abriendo dichos ficheros:

In [9]:
matriz = np.random.randint(0, 1, [100, 3])
df = pd.DataFrame(matriz)
df.to_csv("matrizEj8CSV.csv")
df.to_json("matrizEj8JSON.json")

---
## Ejercicio 9

Investiga qué es la correlación entre columnas. Cuando lo hayas entendido, crea una matriz 10x3 con datos manuales que entre la primera y segunda columna de una correlación de 1 en ambos sentidos. Muestra la matriz y su correlación entre columnas por pantalla:

In [12]:
matriz = np.array([
    [1, 2, 5],
    [2, 3, 7],
    [3, 4, 6],
    [4, 5, 9],
    [5, 6, 3],
    [6, 7, 8],
    [7, 8, 2],
    [8, 9, 10],
    [9, 10, 4],
    [10, 11, 1]
])

df = pd.DataFrame(matriz, columns=['Col1', 'Col2', 'Col3'])
corr = df.corr()
print("Matriz:\n", df, "\n")
print("Correlación:\n", corr)

Matriz:
    Col1  Col2  Col3
0     1     2     5
1     2     3     7
2     3     4     6
3     4     5     9
4     5     6     3
5     6     7     8
6     7     8     2
7     8     9    10
8     9    10     4
9    10    11     1

Correlación:
           Col1      Col2      Col3
Col1  1.000000  1.000000 -0.321212
Col2  1.000000  1.000000 -0.321212
Col3 -0.321212 -0.321212  1.000000

---
## Ejercicio 10

En vuestros ordenadores, MySQLServer debería estar instalado. De no ser así instálalo. Una vez hecho eso, crea un esquema llamado "BDIA" y a continuación lanza las sentencias SQL del fichero "02-Pandas_Tabla_MySQL.sql". Por último, trata de importar los datos desde la base de datos con Pandas en un DataFrame y muéstralos por pantalla:

In [17]:
import mysql.connector

conn = mysql.connector.connect(
    host = "localhost",
    user = "root",
    password = "",
    database = "BDIA"
)

query = "SELECT * FROM tblusuarios;"
df = pd.read_sql(query, conn)
print(df)
conn.close()

    idx  usuario     nombre sexo  nivel                  email      telefono  \
0     1  BRE2271     BRENDA    M      2        brenda@live.com  655-330-5736
1     2  OSC4677      OSCAR    H      3        oscar@gmail.com  655-143-4181
2     3  JOS7086       JOSE    H      3    francisco@gmail.com  655-143-3922
3     4  LUI6115       LUIS    H      0    enrique@outlook.com  655-137-1279
4     5  LUI7072       LUIS    H      1       luis@hotmail.com  655-100-8260
5     6  DAN2832     DANIEL    H      0     daniel@outlook.com  655-145-2586
6     7  JAQ5351  JAQUELINE    M      0  jaqueline@outlook.com  655-330-5514
7     8  ROM6520      ROMAN    H      2        roman@gmail.com  655-330-3263
8     9  BLA9739       BLAS    H      0       blas@hotmail.com  655-330-3871
9    10  JES4752    JESSICA    M      1    jessica@hotmail.com  655-143-6861
10   11  DIA6570      DIANA    M      1         diana@live.com  655-143-3952
11   12  RIC8283    RICARDO    H      2    ricardo@hotmail.com  655-145-6049
12   13  VAL6882  VALENTINA    M      0     valentina@live.com  655-137-4253
13   14  BRE8106     BRENDA    M      3      brenda2@gmail.com  655-100-1351
14   15  LUC4982      LUCIA    M      3        lucia@gmail.com  655-145-4992
15   16  JUA2337       JUAN    H      0       juan@outlook.com  655-100-6517
16   17  ELP2984    ELPIDIO    H      1    elpidio@outlook.com  655-145-9938
17   18  JES9640    JESSICA    M      3      jessica2@live.com  655-330-5143
18   19  LET4015    LETICIA    M      2      leticia@yahoo.com  655-143-4019
19   20  LUI1076       LUIS    H      3         luis2@live.com  655-100-5085
20   21  HUG5441       HUGO    H      2          hugo@live.com  655-137-3935

         marca  compañia  saldo  activo
0      SAMSUNG  IUSACELL  100.0       1
1           LG    TELCEL    0.0       1
2        NOKIA  MOVISTAR  150.0       1
3      SAMSUNG    TELCEL   50.0       1
4        NOKIA  IUSACELL   50.0       0
5         SONY    UNEFON  100.0       1
6   BLACKBERRY      AXEL    0.0       1
7           LG  IUSACELL   50.0       1
8           LG    UNEFON  100.0       1
9      SAMSUNG    TELCEL  500.0       1
10        SONY    UNEFON  100.0       0
11    MOTOROLA  IUSACELL  150.0       1
12  BLACKBERRY      AT&T   50.0       0
13    MOTOROLA    NEXTEL  150.0       1
14  BLACKBERRY  IUSACELL    0.0       1
15     SAMSUNG      AXEL    0.0       0
16    MOTOROLA  MOVISTAR  500.0       1
17        SONY  IUSACELL  200.0       1
18  BLACKBERRY    UNEFON  100.0       1
19        SONY    UNEFON  150.0       1
20    MOTOROLA      AT&T  500.0       1

C:\Users\jperaltaza\AppData\Local\Temp\ipykernel_17932\503458230.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)